language: java
jdk:
    - "oraclejdk8"
    - "openjdk8"
script: "./gradlew build"
after_failure: "./gradlew build --stacktrace --debug"
sudo: false
cache:
    directories:
        - "$HOME/.gradle/caches"
